---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Ensure NTP (for time synchronization) is installed.
  yum: name=ntp state={{ ntp_pkg_state }}
  when: ansible_os_family == 'RedHat'

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp

- name: Ensure NTP is running.
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }}