# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "box-cutter/centos67"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end

end
